1 NONTERMINAL NP^<SQ>+S^<NP>
2 NONTERMINAL WHNP^<WHPP>+PRON
26 NONTERMINAL WHADVP^<SBARQ>
1 NONTERMINAL PP^<ADJP>+ADP
2 NONTERMINAL SBAR
1 NONTERMINAL WHPP^<NP>
1 NONTERMINAL WHNP^<SBARQ>+WHNP^<WHNP>
68 NONTERMINAL CONJ
1447 NONTERMINAL SQ^<SBARQ>
1 NONTERMINAL S^<WHNP>
12 NONTERMINAL S^<NP>+VP^<S>
190 NONTERMINAL NP^<WHNP>
5 NONTERMINAL QP^<NP>
1 NONTERMINAL VP^<SBAR>
1 NONTERMINAL NP^<PP>+VERB
81 NONTERMINAL WHADJP^<WHNP>
19 NONTERMINAL WHNP^<SBAR>+DET
3 NONTERMINAL SBAR^<SBARQ>
513 NONTERMINAL WHNP^<SBARQ>
280 NONTERMINAL PRT
1 NONTERMINAL NP^<S>+NUM
21 NONTERMINAL NP^<SQ>+DET
1 NONTERMINAL NP^<VP>+S^<NP>+VP^<S>
10 NONTERMINAL PP^<ADJP>
1 NONTERMINAL PP^<SBAR>
43 NONTERMINAL NP^<PP>+NUM
33 NONTERMINAL S^<SBAR>
2 NONTERMINAL S^<ADJP>+VP^<S>
3 NONTERMINAL ADVP
3 NONTERMINAL NP^<SQ>+X
17 NONTERMINAL X
1 NONTERMINAL VP^<ADJP>
809 NONTERMINAL WHNP^<SBARQ>+PRON
116 NONTERMINAL VP^<VP>
3 NONTERMINAL ADJP^<NP>+ADJ
22 NONTERMINAL WHNP^<WHNP>
1 NONTERMINAL NP^<ADVP>
3 NONTERMINAL ADVP^<SQ>
7 NONTERMINAL NP^<S>+NOUN
4 NONTERMINAL PP^<ADVP>
16 NONTERMINAL VP^<SQ>+NOUN
23 NONTERMINAL PP^<WHNP>
182 NONTERMINAL NP^<SQ>+NOUN
632 NONTERMINAL NP^<PP>
1 NONTERMINAL WHNP^<SBARQ>+DET
2 NONTERMINAL WHPP^<VP>
1 NONTERMINAL NP^<NP>+ADVP^<NP>
205 NONTERMINAL VP^<SQ>+VERB
1 NONTERMINAL NP^<NP>+PP^<NP>
2 NONTERMINAL WHADVP
1808 NONTERMINAL DET
5 NONTERMINAL VP^<PP>
6 NONTERMINAL SBAR^<NP>+S^<SBAR>
8 NONTERMINAL S^<VP>
42 NONTERMINAL WHADJP^<SBARQ>
85 NONTERMINAL PP^<VP>+ADP
4 NONTERMINAL PP
1 NONTERMINAL PP^<NP>+PRT
8 NONTERMINAL PP^<NP>+ADP
1 NONTERMINAL ADVP^<ADJP>
34 NONTERMINAL VP^<VP>+VERB
1 NONTERMINAL NP^<VP>+NUM
2 NONTERMINAL VP^<NP>+VERB
1 NONTERMINAL S^<NP>
1 NONTERMINAL ADVP^<NP>
1 NONTERMINAL S^<SQ>+VP^<S>
1 NONTERMINAL WHPP^<SBAR>
1 NONTERMINAL WHNP^<WHPP>+DET
22 NONTERMINAL NP^<S>+PRON
2 NONTERMINAL WHNP^<WHNP>+DET
6 NONTERMINAL SBAR^<SQ>
1064 NONTERMINAL NP^<SQ>
1 NONTERMINAL SBARQ^<VP>
5 NONTERMINAL PP^<WHADVP>
13 NONTERMINAL ADJP^<SQ>
3401 NONTERMINAL SBARQ
928 NONTERMINAL NP^<NP>
1 NONTERMINAL NP^<SQ>+NP^<NP>
1 NONTERMINAL NP^<VP>+S^<NP>
7 NONTERMINAL ADJP^<SQ>+ADJ
1 NONTERMINAL NP^<PP>+PRON
5 NONTERMINAL NP^<NP>+NUM
1 NONTERMINAL NX^<NP>
383 NONTERMINAL VP^<SQ>
4 NONTERMINAL ADVP^<VP>
1 NONTERMINAL ADVP^<S>+ADV
1 NONTERMINAL S^<SBAR>+VP^<S>+VERB
297 NONTERMINAL PP^<VP>
27 NONTERMINAL ADVP^<VP>+ADV
9 NONTERMINAL ADVP^<SQ>+ADV
2 NONTERMINAL ADVP^<VP>+ADJ
590 NONTERMINAL PP^<NP>
1 NONTERMINAL PRT^<ADJP>+PRT
5 NONTERMINAL WHNP^<SBAR>+PRON
1 NONTERMINAL WHNP^<ADJP>+PRON
2 NONTERMINAL SBAR^<PP>
3 NONTERMINAL ADJP^<ADJP>
1 NONTERMINAL NP^<PP>+QP^<NP>
376 NONTERMINAL NP^<VP>
6 NONTERMINAL NP^<WHNP>+NOUN
3852 NONTERMINAL NOUN
71 NONTERMINAL VP^<S>
1 NONTERMINAL NP^<VP>+QP^<NP>
34 NONTERMINAL S^<VP>+VP^<S>
2 NONTERMINAL WHADVP^<WHADVP>
2032 NONTERMINAL .
16 NONTERMINAL WHADVP^<SBAR>+ADV
103 NONTERMINAL NUM
10 NONTERMINAL SBAR^<NP>+S^<SBAR>+VP^<S>
1588 NONTERMINAL NP
26 NONTERMINAL VP^<NP>
20 NONTERMINAL WHPP^<SBARQ>
33 NONTERMINAL NP^<S>
19 NONTERMINAL PP^<SQ>+ADP
244 NONTERMINAL ADV
285 NONTERMINAL WHADVP^<SBARQ>+ADV
1010 NONTERMINAL ADP
1 NONTERMINAL VP^<VP>+S^<VP>+VP^<S>
1 NONTERMINAL SBAR^<ADJP>+S^<SBAR>
21 NONTERMINAL WHNP^<WHPP>
3 NONTERMINAL NP^<NP>+DET
56 NONTERMINAL PP^<SQ>
1 NONTERMINAL PP^<VP>+PP^<PP>+ADP
27 NONTERMINAL S^<SBAR>+VP^<S>
3 NONTERMINAL NP^<PP>+ADJ
2 NONTERMINAL WHNP^<VP>
3 NONTERMINAL SBARQ^<SBARQ>
916 NONTERMINAL ADJ
1 NONTERMINAL NP^<SQ>+VERB
1 NONTERMINAL PP^<S>
4 NONTERMINAL PP^<VP>+PRT
634 NONTERMINAL SQ
1 NONTERMINAL NP^<PP>+DET
1 NONTERMINAL ADJP^<WHADJP>
1 NONTERMINAL PP^<VP>+NOUN
1 NONTERMINAL NP^<SQ>+ADJ
2 NONTERMINAL ADVP^<ADVP>
42 NONTERMINAL S
15 NONTERMINAL ADJP
1 NONTERMINAL SBAR^<VP>+VP^<SBAR>
5 NONTERMINAL ADJP^<VP>
14 NONTERMINAL S^<PP>+VP^<S>
296 NONTERMINAL NP^<PP>+NOUN
2 NONTERMINAL WHNP^<SBAR>
83 NONTERMINAL NP^<SQ>+PRON
18 NONTERMINAL SBAR^<VP>
2 NONTERMINAL NP^<VP>+NP^<NP>
99 NONTERMINAL NP^<NP>+NOUN
73 NONTERMINAL PRON
3 NONTERMINAL SBAR^<VP>+S^<SBAR>
13 NONTERMINAL VP^<S>+VERB
26 NONTERMINAL PRT^<VP>+PRT
3 NONTERMINAL PP^<SBARQ>
66 NONTERMINAL NP^<VP>+NOUN
1 NONTERMINAL VP^<SBARQ>
250 NONTERMINAL SQ^<SBARQ>+VP^<SQ>
34 NONTERMINAL SBAR^<NP>
1 NONTERMINAL NP^<VP>+SBAR^<NP>+S^<SBAR>
1 NONTERMINAL SQ^<SBAR>+VP^<SQ>
9 NONTERMINAL ADJP^<VP>+ADJ
199 NONTERMINAL VP
2349 NONTERMINAL VERB
1 NONTERMINAL WHADJP^<VP>
2 NONTERMINAL QP
8 NONTERMINAL NP^<VP>+PRON
44 NONTERMINAL ADJP^<NP>
1 NONTERMINAL NP^<SBARQ>
1 NONTERMINAL ADVP^<NP>+ADV
1 NONTERMINAL SBAR^<SQ>+S^<SBAR>
9 NONTERMINAL WHNP
1 NONTERMINAL PP^<ADJP>+PRT
30 NONTERMINAL PP^<PP>
7 UNARYRULE . _RARE_
1 UNARYRULE PRT _RARE_
7 UNARYRULE VP^<SQ>+VERB mean
43 UNARYRULE NP^<PP>+NUM _RARE_
1 UNARYRULE NP^<PP>+DET _RARE_
2 UNARYRULE NP^<NP>+NOUN President
6 UNARYRULE NOUN horse
3 UNARYRULE WHNP^<SBARQ>+PRON what
1 UNARYRULE PRON it
3 UNARYRULE ADJ Great
19 UNARYRULE VERB get
5 UNARYRULE PP^<NP>+ADP of
3 UNARYRULE PRON what
2 UNARYRULE NP^<PP>+NOUN year
1 UNARYRULE WHADVP^<SBAR>+ADV how
14 UNARYRULE ADJ much
5 UNARYRULE NOUN house
8 UNARYRULE ADVP^<SQ>+ADV _RARE_
7 UNARYRULE VP^<SQ>+VERB have
4 UNARYRULE ADV how
6 UNARYRULE ADJ different
42 UNARYRULE NOUN year
4 UNARYRULE NOUN animal
13 UNARYRULE VERB have
3 UNARYRULE NP^<PP>+ADJ _RARE_
1 UNARYRULE NP^<VP>+NOUN home
5 UNARYRULE ADJ last
1 UNARYRULE VP^<SQ>+VERB get
6 UNARYRULE NOUN language
2 UNARYRULE NP^<SQ>+NOUN president
3 UNARYRULE . <
2 UNARYRULE NP^<NP>+NOUN president
1 UNARYRULE VP^<S>+VERB made
5 UNARYRULE VP^<SQ>+VERB located
1 UNARYRULE PP^<VP>+ADP with
1 UNARYRULE VERB mean
7 UNARYRULE NOUN countries
1 UNARYRULE NP^<VP>+NUM _RARE_
6 UNARYRULE ADJ high
1 UNARYRULE PRT^<VP>+PRT place
5 UNARYRULE NOUN years
5 UNARYRULE NOUN William
11 UNARYRULE NOUN company
7 UNARYRULE NOUN point
5 UNARYRULE ADP before
17 UNARYRULE ADP In
1 UNARYRULE WHNP^<SBAR>+DET which
1 UNARYRULE DET that
2 UNARYRULE PP^<VP>+ADP on
7 UNARYRULE NOUN war
2 UNARYRULE NOUN power
1 UNARYRULE PP^<NP>+PRT to
3 UNARYRULE NP^<PP>+NOUN baseball
4 UNARYRULE ADJ North
5 UNARYRULE NOUN ball
5 UNARYRULE NOUN Mississippi
3 UNARYRULE NOUN types
5 UNARYRULE NOUN song
1 UNARYRULE WHADVP^<SBARQ>+ADV how
1 UNARYRULE NP^<S>+NUM one
77 UNARYRULE NP^<NP>+NOUN _RARE_
4 UNARYRULE VP^<SQ>+VERB begin
5 UNARYRULE NOUN rate
17 UNARYRULE NOUN population
4 UNARYRULE PP^<VP>+PRT to
4 UNARYRULE VERB painted
1 UNARYRULE NOUN France
1 UNARYRULE VERB born
16 UNARYRULE VP^<SQ>+NOUN mean
1 UNARYRULE VP^<VP>+VERB work
23 UNARYRULE VP^<SQ>+VERB born
156 UNARYRULE PRT <s
62 UNARYRULE ADJ first
3 UNARYRULE NOUN London
5 UNARYRULE ADJ South
4 UNARYRULE NOUN miles
1 UNARYRULE WHNP^<WHPP>+PRON what
1 UNARYRULE PP^<SQ>+ADP from
5 UNARYRULE NP^<VP>+PRON _RARE_
1 UNARYRULE ADJ New
38 UNARYRULE VERB has
6 UNARYRULE NOUN America
7 UNARYRULE ADJ British
5 UNARYRULE NOUN battle
9 UNARYRULE ADJ best
5 UNARYRULE NOUN group
9 UNARYRULE NOUN person
118 UNARYRULE . <<
17 UNARYRULE VERB Name
1 UNARYRULE VP^<SQ>+VERB used
6 UNARYRULE ADJ top
38 UNARYRULE NP^<SQ>+PRON you
126 UNARYRULE VERB are
7 UNARYRULE PRT^<VP>+PRT _RARE_
1 UNARYRULE VP^<SQ>+VERB run
6 UNARYRULE NP^<S>+PRON you
2 UNARYRULE NOUN French
1 UNARYRULE PP^<NP>+ADP with
8 UNARYRULE NOUN names
2 UNARYRULE NOUN mean
1 UNARYRULE NP^<NP>+NOUN company
8 UNARYRULE ADP that
78 UNARYRULE ADP for
8 UNARYRULE NOUN colors
1 UNARYRULE NP^<NP>+NOUN rain
11 UNARYRULE NOUN word
4 UNARYRULE NOUN sport
1 UNARYRULE ADJ mountain
9 UNARYRULE ADJ highest
7 UNARYRULE VP^<SQ>+VERB invented
4 UNARYRULE NP^<PP>+NOUN Liberty
16 UNARYRULE ADJ largest
154 UNARYRULE VERB did
1 UNARYRULE NP^<PP>+NOUN school
8 UNARYRULE VP^<S>+VERB _RARE_
1 UNARYRULE NP^<VP>+NOUN French
2 UNARYRULE VERB built
1 UNARYRULE PP^<NP>+ADP for
5 UNARYRULE ADJ common
11 UNARYRULE NOUN sun
3 UNARYRULE NP^<SQ>+X _RARE_
11 UNARYRULE VERB invented
149 UNARYRULE ADV How
11 UNARYRULE NOUN capital
2702 UNARYRULE NOUN _RARE_
2 UNARYRULE NOUN earth
9 UNARYRULE ADJ real
3 UNARYRULE ADJP^<NP>+ADJ _RARE_
4 UNARYRULE NOUN mountain
1 UNARYRULE WHADVP^<SBARQ>+ADV _RARE_
7 UNARYRULE VERB died
3 UNARYRULE NOUN animals
9 UNARYRULE ADJ national
6 UNARYRULE NOUN flight
5 UNARYRULE VERB said
16 UNARYRULE NOUN United
7 UNARYRULE NOUN date
71 UNARYRULE VP^<SQ>+VERB _RARE_
1 UNARYRULE NOUN Texas
247 UNARYRULE VERB was
1 UNARYRULE PP^<VP>+NOUN _RARE_
14 UNARYRULE NOUN color
7 UNARYRULE ADJ average
1 UNARYRULE ADVP^<SQ>+ADV first
5 UNARYRULE NOUN water
1 UNARYRULE NOUN Spanish
14 UNARYRULE VERB used
218 UNARYRULE NP^<PP>+NOUN _RARE_
9 UNARYRULE NOUN John
11 UNARYRULE NP^<SQ>+PRON it
4 UNARYRULE NOUN play
2 UNARYRULE NP^<VP>+NOUN people
1 UNARYRULE PP^<SQ>+ADP with
5 UNARYRULE DET some
18 UNARYRULE VP^<SQ>+VERB called
60 UNARYRULE CONJ and
9 UNARYRULE NOUN number
8 UNARYRULE NOUN character
1 UNARYRULE WHADVP^<SBAR>+ADV _RARE_
1 UNARYRULE PP^<ADJP>+ADP with
6 UNARYRULE NOUN school
5 UNARYRULE VERB located
2 UNARYRULE NP^<NP>+NOUN people
25 UNARYRULE PP^<VP>+ADP in
6 UNARYRULE ADP into
1 UNARYRULE NOUN Liberty
11 UNARYRULE NOUN River
7 UNARYRULE NOUN abbreviation
7 UNARYRULE NOUN home
5 UNARYRULE NOUN party
3 UNARYRULE VERB buried
12 UNARYRULE NOUN War
1 UNARYRULE NP^<PP>+NOUN Vietnam
1 UNARYRULE VERB open
70 UNARYRULE WHADVP^<SBARQ>+ADV How
5 UNARYRULE NOUN star
6 UNARYRULE NOUN currency
1 UNARYRULE VP^<VP>+VERB cost
1 UNARYRULE NP^<NP>+NOUN London
2 UNARYRULE NP^<PP>+NOUN power
1 UNARYRULE NP^<PP>+NOUN French
21 UNARYRULE VP^<SQ>+VERB die
1 UNARYRULE VP^<SQ>+VERB painted
3 UNARYRULE NOUN British
1 UNARYRULE NP^<PP>+NOUN Mississippi
5 UNARYRULE NOUN team
3 UNARYRULE NOUN Australia
5 UNARYRULE NOUN birthstone
7 UNARYRULE VP^<SQ>+VERB built
3 UNARYRULE ADJ long
1 UNARYRULE NP^<VP>+NOUN England
5 UNARYRULE . :
6 UNARYRULE ADP after
2 UNARYRULE NP^<PP>+NOUN Spain
1 UNARYRULE NP^<PP>+PRON it
1 UNARYRULE VP^<SQ>+VERB become
1 UNARYRULE NP^<NP>+NOUN battle
1 UNARYRULE ADVP^<NP>+ADV _RARE_
1 UNARYRULE NP^<VP>+NOUN Alaska
1 UNARYRULE WHNP^<ADJP>+PRON what
5 UNARYRULE NOUN college
15 UNARYRULE NOUN game
9 UNARYRULE ADJP^<VP>+ADJ _RARE_
5 UNARYRULE ADJ black
2 UNARYRULE NP^<PP>+NOUN animals
667 UNARYRULE VERB is
3 UNARYRULE NP^<S>+PRON it
5 UNARYRULE ADJ tallest
3 UNARYRULE NP^<PP>+NOUN France
3 UNARYRULE NP^<SQ>+NOUN water
1 UNARYRULE VP^<SQ>+VERB fear
3 UNARYRULE NP^<SQ>+NOUN people
5 UNARYRULE NOUN percentage
15 UNARYRULE PRON his
32 UNARYRULE NOUN world
11 UNARYRULE NOUN origin
1 UNARYRULE PP^<SQ>+ADP by
2 UNARYRULE ADVP^<VP>+ADJ _RARE_
13 UNARYRULE PRT <
1 UNARYRULE ADJ capital
3 UNARYRULE VP^<SQ>+VERB buried
8 UNARYRULE NOUN woman
12 UNARYRULE ADV far
17 UNARYRULE WHADVP^<SBARQ>+ADV Why
35 UNARYRULE VERB can
11 UNARYRULE VERB makes
1695 UNARYRULE . ?
1 UNARYRULE PRT^<VP>+PRT into
31 UNARYRULE VERB <s
6 UNARYRULE ADJP^<SQ>+ADJ _RARE_
50 UNARYRULE NOUN city
1 UNARYRULE NP^<PP>+NOUN Washington
15 UNARYRULE ADP with
1 UNARYRULE VP^<SQ>+VERB make
1 UNARYRULE NP^<VP>+NOUN Australia
5 UNARYRULE NOUN World
151 UNARYRULE WHNP^<SBARQ>+PRON Who
5 UNARYRULE NOUN leader
10 UNARYRULE NOUN nickname
20 UNARYRULE ADP by
5 UNARYRULE VERB killed
1 UNARYRULE NP^<NP>+NOUN miles
1 UNARYRULE VP^<SQ>+VERB be
7 UNARYRULE NOUN dog
5 UNARYRULE WHNP^<SBAR>+PRON who
1 UNARYRULE PRT^<ADJP>+PRT for
5 UNARYRULE NOUN Lincoln
110 UNARYRULE PRT to
12 UNARYRULE VERB come
29 UNARYRULE NOUN state
1 UNARYRULE VERB name
6 UNARYRULE NOUN governor
6 UNARYRULE NOUN Tower
12 UNARYRULE PP^<VP>+ADP of
2 UNARYRULE NP^<NP>+NOUN types
1 UNARYRULE VP^<SQ>+VERB write
3 UNARYRULE NOUN musical
6 UNARYRULE NOUN Kennedy
4 UNARYRULE ADVP^<VP>+ADV first
5 UNARYRULE NP^<PP>+NOUN Earth
106 UNARYRULE WHADVP^<SBARQ>+ADV When
7 UNARYRULE DET which
5 UNARYRULE ADJ longest
1 UNARYRULE WHNP^<WHPP>+DET which
1 UNARYRULE NP^<NP>+NOUN Spain
1 UNARYRULE VP^<SQ>+VERB founded
11 UNARYRULE NOUN body
22 UNARYRULE ADJ American
1 UNARYRULE NP^<SQ>+ADJ black
25 UNARYRULE ADP as
9 UNARYRULE ADV much
10 UNARYRULE NOUN University
3 UNARYRULE VP^<SQ>+VERB live
1 UNARYRULE NOUN light
1 UNARYRULE NP^<NP>+NOUN state
1 UNARYRULE S^<SBAR>+VP^<S>+VERB _RARE_
7 UNARYRULE NOUN State
167 UNARYRULE NP^<SQ>+NOUN _RARE_
28 UNARYRULE DET Which
6 UNARYRULE VERB use
3 UNARYRULE NP^<PP>+NOUN Mars
1 UNARYRULE NP^<PP>+VERB _RARE_
2 UNARYRULE NP^<S>+PRON they
1 UNARYRULE NP^<S>+NOUN Mars
6 UNARYRULE NOUN West
2 UNARYRULE VERB cost
1 UNARYRULE NOUN I
69 UNARYRULE ADP on
4 UNARYRULE NP^<SQ>+PRON they
14 UNARYRULE ADP at
3 UNARYRULE NP^<S>+PRON _RARE_
76 UNARYRULE NUM _RARE_
4 UNARYRULE NP^<PP>+NOUN Spanish
7 UNARYRULE NOUN term
1 UNARYRULE NP^<NP>+NOUN England
7 UNARYRULE PRON your
6 UNARYRULE NOUN North
2 UNARYRULE ADV only
10 UNARYRULE ADJ fast
2 UNARYRULE PP^<VP>+ADP by
78 UNARYRULE VERB do
22 UNARYRULE . .
2 UNARYRULE WHADVP^<SBAR>+ADV When
1 UNARYRULE NP^<WHNP>+NOUN countries
1 UNARYRULE VP^<SQ>+VERB open
1 UNARYRULE VP^<VP>+VERB form
12 UNARYRULE PP^<VP>+ADP from
21 UNARYRULE ADVP^<VP>+ADV _RARE_
4 UNARYRULE NOUN Africa
7 UNARYRULE PRON _RARE_
8 UNARYRULE NOUN King
3 UNARYRULE NP^<VP>+PRON you
1 UNARYRULE NOUN cost
35 UNARYRULE DET The
1 UNARYRULE NOUN England
8 UNARYRULE NOUN day
43 UNARYRULE NOUN U.S.
15 UNARYRULE NOUN States
10 UNARYRULE VERB play
5 UNARYRULE PRON her
1 UNARYRULE VP^<SQ>+VERB killed
19 UNARYRULE VERB find
1 UNARYRULE NP^<PP>+NOUN rain
1 UNARYRULE VERB begin
10 UNARYRULE VERB become
5 UNARYRULE NP^<S>+PRON he
1 UNARYRULE VP^<S>+VERB did
1 UNARYRULE NP^<SQ>+NOUN Mars
1 UNARYRULE ADVP^<VP>+ADV after
2 UNARYRULE NOUN top
18 UNARYRULE WHNP^<SBAR>+DET that
1 UNARYRULE VP^<VP>+VERB become
7 UNARYRULE NOUN actor
5 UNARYRULE PRON What
272 UNARYRULE ADP in
1 UNARYRULE NP^<PP>+NOUN London
1 UNARYRULE NP^<NP>+NOUN place
41 UNARYRULE NOUN country
3 UNARYRULE ADJ National
21 UNARYRULE ADV most
5 UNARYRULE NP^<WHNP>+NOUN _RARE_
1 UNARYRULE WHNP^<SBARQ>+PRON who
1 UNARYRULE VERB work
14 UNARYRULE PP^<SQ>+ADP in
13 UNARYRULE DET what
6 UNARYRULE NP^<S>+NOUN _RARE_
10 UNARYRULE ADJ old
3 UNARYRULE NOUN form
89 UNARYRULE NOUN name
3 UNARYRULE VP^<SQ>+VERB made
5 UNARYRULE VERB had
1 UNARYRULE PP^<VP>+PP^<PP>+ADP in
8 UNARYRULE NOUN US
1 UNARYRULE ADVP^<S>+ADV _RARE_
3 UNARYRULE NOUN place
8 UNARYRULE ADJ tall
2 UNARYRULE ADV about
38 UNARYRULE ADP from
1 UNARYRULE NP^<PP>+NOUN Johnson
8 UNARYRULE NOUN book
14 UNARYRULE PRON its
1 UNARYRULE ADVP^<VP>+ADV best
1 UNARYRULE NP^<SQ>+NOUN light
4 UNARYRULE ADJ French
53 UNARYRULE NP^<VP>+NOUN _RARE_
6 UNARYRULE NUM four
17 UNARYRULE X _RARE_
2 UNARYRULE NP^<SQ>+NOUN Alaska
5 UNARYRULE NOUN address
2 UNARYRULE NP^<PP>+NOUN Africa
6 UNARYRULE NOUN bird
2 UNARYRULE PP^<VP>+ADP at
5 UNARYRULE NOUN show
5 UNARYRULE NOUN eye
8 UNARYRULE NOUN car
1 UNARYRULE NOUN start
9 UNARYRULE PRT^<VP>+PRT out
1 UNARYRULE NP^<SQ>+VERB called
13 UNARYRULE NOUN New
5 UNARYRULE NOUN life
1 UNARYRULE NOUN Spain
6 UNARYRULE NOUN money
23 UNARYRULE PP^<VP>+ADP for
90 UNARYRULE WHADVP^<SBARQ>+ADV Where
1 UNARYRULE ADV Why
1 UNARYRULE VP^<SQ>+VERB cost
10 UNARYRULE VERB say
8 UNARYRULE NOUN movie
108 UNARYRULE VERB does
4 UNARYRULE NP^<PP>+NOUN Canada
6 UNARYRULE NOUN system
2 UNARYRULE VP^<SQ>+VERB use
7 UNARYRULE ADJ oldest
1 UNARYRULE NP^<NP>+NUM two
21 UNARYRULE NP^<SQ>+DET there
653 UNARYRULE WHNP^<SBARQ>+PRON What
6 UNARYRULE VERB live
2 UNARYRULE NP^<PP>+NOUN light
5 UNARYRULE NOUN Vietnam
2 UNARYRULE NP^<PP>+NOUN people
7 UNARYRULE NOUN river
1 UNARYRULE PP^<NP>+ADP in
1 UNARYRULE NP^<SQ>+NOUN France
1 UNARYRULE NOUN use
2 UNARYRULE NP^<VP>+NOUN power
10 UNARYRULE VERB take
390 UNARYRULE DET What
13 UNARYRULE NOUN people
2 UNARYRULE WHNP^<WHNP>+DET Which
6 UNARYRULE VERB founded
4 UNARYRULE VERB start
5 UNARYRULE VERB given
1 UNARYRULE NP^<PP>+NOUN animal
12 UNARYRULE WHADVP^<SBAR>+ADV when
7 UNARYRULE NOUN York
3 UNARYRULE NOUN Great
3 UNARYRULE NOUN Canada
1 UNARYRULE NP^<NP>+NUM one
64 UNARYRULE . ,
14 UNARYRULE VERB called
4 UNARYRULE VERB write
1084 UNARYRULE DET the
17 UNARYRULE DET _RARE_
18 UNARYRULE VERB made
5 UNARYRULE PP^<VP>+ADP into
39 UNARYRULE ADP _RARE_
6 UNARYRULE NP^<PP>+NOUN water
6 UNARYRULE NOUN George
8 UNARYRULE ADJ famous
1 UNARYRULE VP^<VP>+VERB invented
3 UNARYRULE VP^<SQ>+VERB work
3 UNARYRULE NP^<PP>+NOUN Texas
5 UNARYRULE NOUN difference
5 UNARYRULE ADP about
8 UNARYRULE ADP between
1 UNARYRULE NP^<PP>+NOUN dog
8 UNARYRULE PRON their
1 UNARYRULE WHNP^<SBARQ>+DET Which
2 UNARYRULE VP^<NP>+VERB _RARE_
1 UNARYRULE PP^<VP>+ADP as
13 UNARYRULE NOUN fear
4 UNARYRULE NP^<PP>+NOUN earth
20 UNARYRULE VERB were
11 UNARYRULE VERB make
526 UNARYRULE ADJ _RARE_
7 UNARYRULE ADJ only
1 UNARYRULE NP^<NP>+NOUN light
8 UNARYRULE NOUN moon
4 UNARYRULE NOUN rain
5 UNARYRULE NUM one
15 UNARYRULE NOUN president
3 UNARYRULE NP^<NP>+NOUN home
477 UNARYRULE VERB _RARE_
3 UNARYRULE NP^<NP>+NUM _RARE_
5 UNARYRULE VERB causes
1 UNARYRULE WHNP^<SBARQ>+PRON Which
5 UNARYRULE NOUN Johnson
1 UNARYRULE VP^<SQ>+VERB form
5 UNARYRULE ADJ female
16 UNARYRULE VERB known
2 UNARYRULE VP^<SQ>+VERB play
2 UNARYRULE NP^<PP>+NOUN office
1 UNARYRULE NP^<PP>+NOUN sport
5 UNARYRULE NOUN South
1 UNARYRULE NOUN work
2 UNARYRULE ADJ musical
1 UNARYRULE PP^<ADJP>+PRT to
1 UNARYRULE VP^<VP>+VERB run
5 UNARYRULE ADV long
3 UNARYRULE NOUN office
3 UNARYRULE PRON I
6 UNARYRULE ADJ Spanish
3 UNARYRULE VERB run
1 UNARYRULE WHNP^<WHPP>+PRON _RARE_
4 UNARYRULE NP^<VP>+NOUN place
13 UNARYRULE NOUN President
5 UNARYRULE VERB wrote
2 UNARYRULE PP^<SQ>+ADP on
10 UNARYRULE NOUN Day
4 UNARYRULE VP^<SQ>+VERB do
5 UNARYRULE ADP out
1 UNARYRULE NP^<NP>+DET that
1 UNARYRULE NP^<PP>+NOUN America
10 UNARYRULE VERB call
8 UNARYRULE VERB being
69 UNARYRULE ADJ many
30 UNARYRULE DET an
30 UNARYRULE NP^<SQ>+PRON I
10 UNARYRULE NOUN kind
3 UNARYRULE NP^<S>+PRON I
8 UNARYRULE NOUN St.
380 UNARYRULE ADP of
2 UNARYRULE NP^<PP>+NOUN miles
5 UNARYRULE PRON my
1 UNARYRULE NP^<PP>+NOUN average
1 UNARYRULE ADJ home
25 UNARYRULE VP^<VP>+VERB _RARE_
1 UNARYRULE ADJ West
2 UNARYRULE NP^<PP>+NOUN Australia
1 UNARYRULE VP^<VP>+VERB find
2 UNARYRULE CONJ _RARE_
2 UNARYRULE NP^<PP>+NOUN England
5 UNARYRULE ADJ European
7 UNARYRULE PRT^<VP>+PRT up
1 UNARYRULE ADJP^<SQ>+ADJ open
1 UNARYRULE NOUN run
5 UNARYRULE VERB been
6 UNARYRULE NOUN Washington
3 UNARYRULE NP^<PP>+NOUN Alaska
1 UNARYRULE NP^<NP>+NOUN Texas
9 UNARYRULE NOUN film
2 UNARYRULE ADV Where
5 UNARYRULE ADJ fastest
5 UNARYRULE VERB win
1 UNARYRULE NP^<SQ>+NOUN Spain
10 UNARYRULE NOUN baseball
3 UNARYRULE NOUN Earth
2 UNARYRULE NOUN National
118 UNARYRULE . ``
198 UNARYRULE DET a
6 UNARYRULE CONJ or
1 UNARYRULE PRT^<VP>+PRT on
37 UNARYRULE ADV _RARE_
1 UNARYRULE NP^<PP>+NOUN president
16 UNARYRULE NUM two
2 UNARYRULE VP^<VP>+VERB open
1 UNARYRULE VP^<SQ>+VERB start
20 UNARYRULE VERB stand
2 UNARYRULE NP^<NP>+DET some
14 UNARYRULE ADJ most
3 UNARYRULE VP^<S>+VERB died
5 UNARYRULE NOUN American
5 UNARYRULE VERB should
1 UNARYRULE NP^<SQ>+NOUN color
12 UNARYRULE VERB be
42 BINARYRULE SBARQ WHADJP^<SBARQ> SBARQ
18 BINARYRULE WHPP^<SBARQ> ADP WHNP^<WHPP>
16 BINARYRULE SBAR^<NP> WHNP^<SBAR>+DET S^<SBAR>+VP^<S>
1 BINARYRULE VP NP^<VP> PP^<VP>+NOUN
1 BINARYRULE VP^<NP> VERB PP^<VP>+ADP
1 BINARYRULE NP^<VP> NP^<NP>+NUM PP^<NP>+ADP
6 BINARYRULE NP^<PP> NOUN NUM
2 BINARYRULE NP ADJP^<NP> NP^<NP>
5 BINARYRULE NP^<NP> NUM NOUN
10 BINARYRULE NP^<VP> NP^<NP> SBAR^<NP>
1 BINARYRULE S . S
1 BINARYRULE VP^<VP> VP^<VP> VP
168 BINARYRULE SQ NP^<SQ> VP^<SQ>
3 BINARYRULE PP^<SQ> ADP NP^<PP>+NUM
21 BINARYRULE NP CONJ NOUN
1 BINARYRULE NP^<VP>+NP^<NP> . NP
8 BINARYRULE SQ NP^<SQ>+NOUN PP^<SQ>+ADP
1 BINARYRULE NP^<SBARQ> NP^<NP> NP
8 BINARYRULE NP^<WHNP> NUM NOUN
2 BINARYRULE ADJP^<VP> . ADJP
95 BINARYRULE NP NOUN PRT
1 BINARYRULE PP^<ADVP> PRT NP^<PP>
1 BINARYRULE SQ^<SBARQ>+VP^<SQ> VERB S^<VP>
1 BINARYRULE NP^<SQ> NP^<NP>+NOUN VP^<NP>+VERB
1 BINARYRULE ADJP ADJ .
1 BINARYRULE SBARQ WHNP^<SBARQ>+DET SBARQ
12 BINARYRULE NP^<SQ> NP^<NP> SBAR^<NP>
1 BINARYRULE S^<SQ>+VP^<S> VP^<VP> VP
2 BINARYRULE VP CONJ VP^<VP>
9 BINARYRULE SQ^<SBARQ>+VP^<SQ> VERB VP^<VP>
1 BINARYRULE NP^<VP>+S^<NP>+VP^<S> VERB VP
1 BINARYRULE SBAR^<NP>+S^<SBAR> NP^<S> VP^<S>+VERB
11 BINARYRULE NP^<NP> NOUN PP^<NP>
4 BINARYRULE S . .
1 BINARYRULE VP^<SQ> VP^<VP> SBAR^<VP>
1 BINARYRULE NP^<PP> NP^<NP>+NOUN VP^<NP>+VERB
2 BINARYRULE PP^<PP> ADP NP^<PP>+NUM
2 BINARYRULE VP^<S> PRT VP^<VP>
2 BINARYRULE ADJP CONJ ADJ
4 BINARYRULE WHNP^<SBARQ> DET WHNP
1 BINARYRULE SBARQ WHNP^<SBARQ>+PRON SQ^<SBARQ>+VP^<SQ>
2 BINARYRULE NP^<SQ> NOUN NP^<NP>
1 BINARYRULE SBAR SQ^<SBAR>+VP^<SQ> .
7 BINARYRULE ADJP^<SQ> ADJ PP^<ADJP>
1 BINARYRULE SBARQ NP^<SBARQ> .
4 BINARYRULE VP^<NP> VERB NP^<VP>
2 BINARYRULE VP NP^<VP>+PRON NP^<VP>
28 BINARYRULE PP^<VP> ADP NP^<PP>+NUM
3 BINARYRULE SQ NP^<SQ>+PRON PP^<SQ>
1 BINARYRULE VP^<SBARQ> VERB NP^<VP>+PRON
4 BINARYRULE VP^<SQ> ADVP^<VP>+ADV VP
1 BINARYRULE VP . S^<VP>+VP^<S>
2 BINARYRULE WHADVP ADV ADV
4 BINARYRULE SQ NP^<SQ>+PRON SQ
3 BINARYRULE PP ADP NP^<PP>
1 BINARYRULE NP^<S> NP^<NP> PP^<NP>
4 BINARYRULE S VP^<S> S
10 BINARYRULE NP^<SQ> NP^<NP> SBAR^<NP>+S^<SBAR>+VP^<S>
3 BINARYRULE NP^<VP> NUM NOUN
1 BINARYRULE ADJP NUM NOUN
5 BINARYRULE NP^<VP> PRON NP
1 BINARYRULE SBARQ WHNP^<SBARQ>+WHNP^<WHNP> SBARQ
2 BINARYRULE VP NP^<VP> NP^<VP>
1 BINARYRULE ADVP^<NP> ADV .
2 BINARYRULE NP^<SQ> NOUN PP^<NP>
2 BINARYRULE SQ NP^<SQ> VERB
3 BINARYRULE NP^<PP> DET NUM
36 BINARYRULE PP^<SQ> ADP NP^<PP>
1 BINARYRULE NP^<VP> VERB NOUN
14 BINARYRULE NP^<PP> NP^<NP>+NOUN NP
2 BINARYRULE S^<VP>+VP^<S> . VP
6 BINARYRULE NP^<VP> ADJ NP
20 BINARYRULE SBARQ WHPP^<SBARQ> SBARQ
1 BINARYRULE NP^<SQ> ADJP^<NP> NP
5 BINARYRULE SQ NP^<SQ> SQ
1 BINARYRULE SBAR^<ADJP>+S^<SBAR> NP^<S>+PRON VP^<S>
1 BINARYRULE SBAR^<NP>+S^<SBAR>+VP^<S> PRT VP^<VP>+VERB
8 BINARYRULE PP^<WHNP> ADP NP^<PP>+NOUN
1 BINARYRULE NP^<VP>+SBAR^<NP>+S^<SBAR> ADVP^<S>+ADV S
7 BINARYRULE S^<VP>+VP^<S> PRT VP^<VP>+VERB
5 BINARYRULE NP^<NP> NP^<NP>+NOUN PP^<NP>
1 BINARYRULE VP NP^<VP>+NOUN VP^<VP>+VERB
1 BINARYRULE NP^<NP> ADJP^<NP> NP^<NP>
1 BINARYRULE SQ VP^<SQ>+VERB SQ
1 BINARYRULE ADVP^<VP> ADV ADVP
1 BINARYRULE VP PRT^<VP>+PRT SBAR^<VP>
211 BINARYRULE NP^<SQ> DET NP
2 BINARYRULE ADJP^<SQ> ADJ S^<ADJP>+VP^<S>
68 BINARYRULE VP^<SQ> VERB PP^<VP>+ADP
39 BINARYRULE WHADJP^<SBARQ> ADV ADJ
2 BINARYRULE VP PP^<VP> NP^<VP>
9 BINARYRULE SBAR^<NP> ADP S^<SBAR>
1 BINARYRULE SQ . PP^<SQ>
1 BINARYRULE VP^<SQ> ADVP^<VP>+ADV VERB
1 BINARYRULE WHPP^<NP> ADP WHNP^<WHPP>
1 BINARYRULE VP^<VP> VERB ADVP^<VP>+ADV
9 BINARYRULE SQ NP^<SQ> PP^<SQ>
3 BINARYRULE NP^<SQ> NP^<NP> SBAR^<NP>+S^<SBAR>
1 BINARYRULE WHADJP^<VP> ADV ADJ
88 BINARYRULE NP^<VP> DET NP
4 BINARYRULE SBARQ WHNP^<SBARQ> SQ^<SBARQ>
1 BINARYRULE PP^<VP> ADP PP
4 BINARYRULE S^<SBAR> NP^<S>+NOUN VP^<S>
1 BINARYRULE VP PRT^<VP>+PRT WHPP^<VP>
1 BINARYRULE SBARQ^<VP> WHNP^<SBARQ> SQ^<SBARQ>+VP^<SQ>
2 BINARYRULE PP^<SBARQ> ADP NP^<PP>+NOUN
2 BINARYRULE NP^<NP> NP^<NP> NP^<NP>+NOUN
1 BINARYRULE ADVP^<ADJP> ADV ADV
3 BINARYRULE SBAR^<VP> WHADVP^<SBAR>+ADV S^<SBAR>+VP^<S>
1 BINARYRULE SQ ADJP^<SQ>+ADJ PP^<SQ>
1 BINARYRULE S^<PP>+VP^<S> VERB ADJP^<VP>
36 BINARYRULE NP^<SQ> NP^<NP> NOUN
318 BINARYRULE NP^<NP> DET NOUN
3 BINARYRULE NP^<VP> QP^<NP> NOUN
5 BINARYRULE NP^<NP> . NOUN
1 BINARYRULE VP^<SQ> VP^<VP> NP^<VP>
1 BINARYRULE S NP^<S>+PRON VP^<S>+VERB
3 BINARYRULE NP VERB NP
1 BINARYRULE WHNP^<SBARQ> ADV ADV
5 BINARYRULE PP^<VP> ADP PP^<PP>
1 BINARYRULE PP^<SQ> PRT VP^<PP>
8 BINARYRULE NP^<VP> NP^<NP>+NOUN PP^<NP>
1 BINARYRULE NP^<SQ> NUM NOUN
5 BINARYRULE WHNP^<SBARQ> DET NP^<WHNP>+NOUN
1 BINARYRULE ADVP^<ADVP> ADV ADV
17 BINARYRULE NP^<VP> PRON NOUN
1 BINARYRULE SQ ADV VP^<SQ>
1 BINARYRULE VP^<VP> VERB ADJP^<VP>
2 BINARYRULE NP^<SQ> NOUN PRT
1 BINARYRULE PP^<SBARQ> ADP NP^<PP>
3 BINARYRULE NP^<VP> NOUN .
1 BINARYRULE NP^<NP> NP^<NP> VP^<NP>
5 BINARYRULE NP CONJ NP
11 BINARYRULE S^<SBAR> NP^<S> VP^<S>
356 BINARYRULE PP^<NP> ADP NP^<PP>
5 BINARYRULE SBAR^<NP> WHNP^<SBAR>+PRON S^<SBAR>+VP^<S>
1 BINARYRULE NP NP^<NP> PP^<NP>
1 BINARYRULE SQ NP^<SQ>+ADJ SQ
1 BINARYRULE ADJP^<NP> ADJ NOUN
7 BINARYRULE NP^<VP> NP^<NP> NP^<NP>
14 BINARYRULE NP^<PP> NP^<NP> NP^<NP>
1 BINARYRULE NP^<S> NP^<NP> NOUN
9 BINARYRULE VP^<VP> VERB NP^<VP>+NOUN
5 BINARYRULE NP^<SQ> NP^<NP>+NOUN PP^<NP>
2 BINARYRULE NP^<WHNP> NP^<NP> PP^<NP>
2 BINARYRULE WHPP^<VP> ADP WHNP^<WHPP>
3 BINARYRULE WHADJP^<WHNP> ADV ADV
1 BINARYRULE ADJP^<NP> ADV ADJP^<ADJP>
1 BINARYRULE VP VERB NP^<VP>+NOUN
1 BINARYRULE S^<VP> NP^<S> VP^<S>
1 BINARYRULE SBAR^<PP> WHADVP^<SBAR>+ADV S^<SBAR>
1 BINARYRULE NP^<SQ>+NP^<NP> NP^<NP> PP^<NP>
10 BINARYRULE NP^<PP> NP^<NP>+NOUN PP^<NP>
1 BINARYRULE VP^<SQ> VERB SBAR^<VP>+VP^<SBAR>
1 BINARYRULE PP^<NP> PRT NP^<PP>+NOUN
2 BINARYRULE NP^<S> . NOUN
5 BINARYRULE VP^<VP> VERB S^<VP>+VP^<S>
1 BINARYRULE ADVP ADV PP^<ADVP>
2 BINARYRULE SQ PP^<SQ> PP^<SQ>
1 BINARYRULE NP ADJP^<NP> NP^<NP>+NOUN
1 BINARYRULE ADVP^<VP> ADV PP^<ADVP>
2 BINARYRULE S^<ADJP>+VP^<S> PRT VP^<VP>
5 BINARYRULE VP^<SQ> VERB VP^<VP>
1 BINARYRULE VP VERB S^<VP>+VP^<S>
20 BINARYRULE VP PP^<VP> PP^<VP>
1 BINARYRULE VP^<VP> ADV VERB
3 BINARYRULE PP^<ADJP> ADP NP^<PP>
1 BINARYRULE NP NP^<NP>+NOUN .
1 BINARYRULE VP^<VP> . VP
4 BINARYRULE WHNP ADJ NOUN
11 BINARYRULE PP^<SQ> ADP NP^<PP>+NOUN
1 BINARYRULE PP^<ADJP> ADP VP^<PP>
3 BINARYRULE NP^<SQ> NOUN NUM
1 BINARYRULE NP^<NP> X NP
1 BINARYRULE ADJP^<NP> NOUN ADJP
7 BINARYRULE VP^<SQ> VERB PRT^<VP>+PRT
6 BINARYRULE S NP^<S> S
2 BINARYRULE SQ^<SBARQ>+VP^<SQ> ADVP^<VP>+ADV VP
2 BINARYRULE VP^<SQ> ADVP^<VP>+ADV VP^<VP>
10 BINARYRULE PP^<NP> PRT NP^<PP>
2 BINARYRULE SBAR^<NP>+S^<SBAR> NP^<S> VP^<S>
1 BINARYRULE VP NP^<VP>+NOUN VP^<VP>
3 BINARYRULE VP NP^<VP> PP^<VP>+ADP
78 BINARYRULE WHADJP^<WHNP> ADV ADJ
1 BINARYRULE NP^<SQ> PRON NP
1 BINARYRULE ADJP^<VP> ADV ADJ
46 BINARYRULE VP NP^<VP> PP^<VP>
63 BINARYRULE SQ^<SBARQ> VERB VP^<SQ>
1 BINARYRULE S^<VP>+VP^<S> VERB VP
8 BINARYRULE SQ ADVP^<SQ>+ADV VP^<SQ>
1 BINARYRULE NP^<SQ> NP^<NP>+NOUN VP^<NP>
2 BINARYRULE SQ^<SBARQ> VERB ADVP^<SQ>
1 BINARYRULE ADJP X .
1 BINARYRULE NP^<NP> NP^<NP> NP^<NP>
1 BINARYRULE ADVP ADV ADVP^<ADVP>
6 BINARYRULE NP^<NP> DET ADJ
1 BINARYRULE SBAR^<VP> WHNP^<SBAR> S^<SBAR>
10 BINARYRULE NP^<SQ> NP^<NP> S^<NP>+VP^<S>
1 BINARYRULE SQ^<SBARQ>+VP^<SQ> VP^<VP> VP
1 BINARYRULE VP CONJ VP
2 BINARYRULE SQ NP^<SQ>+NOUN NP^<SQ>
11 BINARYRULE NP^<VP> . NP
2 BINARYRULE NP^<WHNP> NP^<NP> NP
1 BINARYRULE VP^<S> NOUN NP^<VP>+NOUN
2 BINARYRULE NP^<NP> NP^<NP> PRT
2 BINARYRULE SBARQ . .
1 BINARYRULE SBAR^<NP> WHNP^<SBAR>+DET VP^<SBAR>
1 BINARYRULE VP^<S> VERB NP^<VP>+PRON
16 BINARYRULE ADJP^<NP> ADV ADJ
2 BINARYRULE NP . NUM
1 BINARYRULE PP^<NP> ADP SBAR^<PP>
1 BINARYRULE NP^<PP> NP^<NP> NP^<NP>+PP^<NP>
32 BINARYRULE NP^<SQ> NOUN NP
5 BINARYRULE NP^<S> DET NP
4 BINARYRULE SQ NP^<SQ> SBAR^<SQ>
1 BINARYRULE VP VERB ADVP^<VP>+ADJ
1 BINARYRULE ADJP^<NP> ADV VERB
1 BINARYRULE VP^<VP> VERB NP^<VP>+PRON
4 BINARYRULE ADJP^<NP> DET ADJ
1 BINARYRULE VP NP^<VP> ADVP^<VP>
1 BINARYRULE NP . NP^<NP>+NUM
25 BINARYRULE S VP^<S> .
28 BINARYRULE SQ NP^<SQ>+NOUN VP^<SQ>+VERB
1 BINARYRULE NP^<WHNP> NP^<NP>+NOUN SBAR^<NP>
5 BINARYRULE NP^<WHNP> ADJP^<NP> NOUN
1 BINARYRULE SQ NP^<SQ>+NOUN ADJP^<SQ>
4 BINARYRULE ADJP^<NP> ADJ ADJP
2 BINARYRULE WHNP^<WHPP> PRON NOUN
69 BINARYRULE NP^<VP> NP^<NP> PP^<NP>
1 BINARYRULE NP^<WHNP> NOUN PRT
72 BINARYRULE VP^<SQ> VERB NP^<VP>
1 BINARYRULE VP . S^<VP>
10 BINARYRULE VP^<SQ> VERB SBAR^<VP>
1 BINARYRULE WHADVP^<SBARQ> ADV WHADVP
1 BINARYRULE S^<WHNP> NP^<S> VP^<S>+VERB
1 BINARYRULE NP^<SQ> NP^<NP> ADJ
1 BINARYRULE QP^<NP> DET NUM
71 BINARYRULE SQ^<SBARQ> VERB NP^<SQ>+NOUN
55 BINARYRULE NP^<PP> NP^<NP> PP^<NP>
2 BINARYRULE ADJP^<ADJP> DET ADJ
1 BINARYRULE WHNP NOUN ADJ
57 BINARYRULE PP^<VP> ADP NP^<PP>+NOUN
3 BINARYRULE NP NP^<NP>+NOUN NP
1 BINARYRULE NP^<WHNP> NP^<NP> NP^<NP>
7 BINARYRULE NP . NP^<NP>
1 BINARYRULE SBAR^<SBARQ> WHADVP^<SBAR>+ADV S^<SBAR>
1 BINARYRULE NP . S^<NP>+VP^<S>
4 BINARYRULE VP^<S> VERB VP^<VP>
1 BINARYRULE SBAR^<NP> WHADVP^<SBAR>+ADV S^<SBAR>
14 BINARYRULE NP^<SQ> NP^<NP> VP^<NP>
2 BINARYRULE WHNP^<SBARQ> WHADJP^<WHNP> WHNP
1 BINARYRULE SQ^<SBARQ>+VP^<SQ> VERB ADVP^<VP>+ADV
7 BINARYRULE SBARQ . SBARQ
1 BINARYRULE ADJP^<SQ> ADJ NOUN
2 BINARYRULE NP^<VP> NUM NP
15 BINARYRULE SQ^<SBARQ>+VP^<SQ> VERB NP^<VP>+NOUN
2 BINARYRULE WHNP^<WHNP> DET NP^<WHNP>
2 BINARYRULE ADVP^<VP> ADV ADV
1 BINARYRULE VP^<VP> VERB .
10 BINARYRULE PP^<PP> ADP NP^<PP>
5 BINARYRULE NP^<SQ> NP^<NP> PP^<NP>+ADP
1 BINARYRULE VP NP^<VP>+NOUN PRT^<VP>+PRT
2 BINARYRULE QP^<NP> ADV NUM
2 BINARYRULE VP^<SQ> ADJ VP
1 BINARYRULE ADJP . SBAR^<ADJP>+S^<SBAR>
15 BINARYRULE NP^<PP> . NP
2 BINARYRULE VP ADJP^<VP> PP^<VP>
2 BINARYRULE VP^<SQ> ADVP^<VP>+ADV VP^<VP>+VERB
7 BINARYRULE S^<NP>+VP^<S> PRT VP^<VP>
5 BINARYRULE NP^<VP> NP^<NP> VP^<NP>
2 BINARYRULE VP^<VP> PRT VP^<VP>+VERB
1 BINARYRULE ADJP^<NP> . ADJ
3 BINARYRULE VP PRT^<VP>+PRT NP^<VP>
1 BINARYRULE SQ ADJP^<SQ> SBAR^<SQ>
1 BINARYRULE S^<PP>+VP^<S> VERB NP^<VP>+NOUN
1 BINARYRULE S^<NP>+VP^<S> VERB VP
17 BINARYRULE WHADVP^<SBARQ> ADV ADV
2 BINARYRULE NP ADJ ADJ
1 BINARYRULE NP^<VP> NP^<NP>+NOUN PP^<NP>+ADP
1 BINARYRULE NP NOUN ADV
1 BINARYRULE VP^<SQ> VERB NP^<VP>+SBAR^<NP>+S^<SBAR>
18 BINARYRULE SQ^<SBARQ> VERB PP^<SQ>
3 BINARYRULE WHNP NOUN NOUN
1 BINARYRULE NP^<SQ> NOUN PP^<NP>+ADP
1 BINARYRULE PP^<VP> PRT NP^<PP>+NUM
1 BINARYRULE SBAR^<NP>+S^<SBAR> NP^<S>+PRON VP^<S>
6 BINARYRULE NP^<S> NOUN NOUN
1 BINARYRULE WHPP^<SBARQ> PRT WHNP^<WHPP>+PRON
619 BINARYRULE SQ^<SBARQ> VERB SQ
155 BINARYRULE WHNP^<SBARQ> DET NP^<WHNP>
10 BINARYRULE S^<SBAR> NP^<S>+PRON VP^<S>
1 BINARYRULE SQ^<SBARQ>+VP^<SQ> ADVP^<VP> VP^<VP>
3 BINARYRULE SBARQ^<SBARQ> WHNP^<SBARQ> SQ^<SBARQ>
1 BINARYRULE VP PP^<VP> WHPP^<VP>
2 BINARYRULE NP^<S> . NP
7 BINARYRULE NP^<PP> NP^<NP> SBAR^<NP>
1 BINARYRULE WHNP^<SBAR> PRON NOUN
1 BINARYRULE SBARQ SBARQ^<SBARQ> .
2 BINARYRULE SBARQ SQ^<SBARQ> SBARQ
1 BINARYRULE S^<SBAR>+VP^<S> VERB NP^<VP>+NOUN
6 BINARYRULE NP^<SQ> ADJ NP
53 BINARYRULE NP^<NP> NOUN NOUN
2 BINARYRULE NP^<SQ> NP^<NP> NP^<NP>+NOUN
5 BINARYRULE NP^<SQ> PRON NOUN
1 BINARYRULE VP ADJP^<VP>+ADJ PP^<VP>
2 BINARYRULE VP^<VP> VERB ADJP^<VP>+ADJ
1 BINARYRULE NP ADV .
1 BINARYRULE VP^<NP> PRT VP
1 BINARYRULE VP^<S> VERB S^<VP>+VP^<S>
11 BINARYRULE VP^<VP> VERB VP^<VP>
1 BINARYRULE VP^<SQ> VERB NP^<VP>+PRON
1 BINARYRULE VP NP^<VP> VP^<VP>+VERB
1 BINARYRULE VP^<VP>+S^<VP>+VP^<S> PRT VP^<VP>
12 BINARYRULE VP^<VP> VERB VP
1 BINARYRULE VP^<VP> VERB VP^<VP>+VERB
5 BINARYRULE PP^<PP> PRT NP^<PP>+NOUN
1 BINARYRULE NP^<NP> ADJP^<NP> NOUN
1 BINARYRULE NP^<SQ> NP^<NP>+NUM PP^<NP>
2 BINARYRULE SBARQ CONJ SBARQ
1 BINARYRULE NP ADJP^<NP> PP^<NP>
1 BINARYRULE S^<SBAR>+VP^<S> PRT VP^<VP>
1 BINARYRULE NP . PP^<NP>
2 BINARYRULE VP PRT^<VP>+PRT PP^<VP>+ADP
6 BINARYRULE NP^<PP> PRON NP
3 BINARYRULE NP^<VP> ADJP^<NP> NP^<NP>
3 BINARYRULE WHNP^<SBARQ> PRON WHNP
1 BINARYRULE VP^<SQ> NOUN PP^<VP>
1 BINARYRULE NP^<SQ>+S^<NP> NP^<S> VP^<S>
1 BINARYRULE SQ^<SBARQ> VERB VP^<SQ>+VERB
2 BINARYRULE VP ADVP^<VP>+ADV VP^<VP>
1 BINARYRULE SQ ADVP^<SQ>+ADV VP^<SQ>+VERB
1 BINARYRULE NP^<SQ> DET NP^<NP>
1 BINARYRULE NP^<SQ> NP^<NP> WHPP^<NP>
15 BINARYRULE PP^<WHNP> ADP NP^<PP>
1 BINARYRULE SBAR^<PP> WHADVP^<SBAR>+ADV S^<SBAR>+VP^<S>
6 BINARYRULE NP DET NOUN
278 BINARYRULE NP^<NP> DET NP
1 BINARYRULE PP^<NP> ADP NP^<PP>+ADJ
1 BINARYRULE SBAR^<NP> WHNP^<SBAR>+DET S^<SBAR>+VP^<S>+VERB
1 BINARYRULE VP^<SQ> VERB NP^<VP>+S^<NP>+VP^<S>
1 BINARYRULE SQ NP^<SQ>+NP^<NP> VP^<SQ>+VERB
1 BINARYRULE SQ^<SBARQ> VERB SBAR^<SQ>+S^<SBAR>
34 BINARYRULE NP^<PP> ADJ NOUN
1 BINARYRULE ADJP ADJ ADJP
1 BINARYRULE WHNP^<WHPP> ADV ADV
1 BINARYRULE VP NP^<VP> ADJP^<VP>+ADJ
3 BINARYRULE NP^<WHNP> NP^<NP>+NOUN PP^<NP>
1 BINARYRULE VP NP^<VP> VP^<VP>+S^<VP>+VP^<S>
1 BINARYRULE SBAR^<VP> WHADVP^<SBAR>+ADV PP^<SBAR>
1 BINARYRULE PP^<VP> ADP NP^<PP>+QP^<NP>
12 BINARYRULE VP^<NP> VERB PP^<VP>
1 BINARYRULE VP^<SQ> VERB ADVP^<VP>
1 BINARYRULE WHNP NP^<WHNP> NOUN
1 BINARYRULE NP^<S> PRON NOUN
438 BINARYRULE NP NOUN NOUN
67 BINARYRULE NP^<SQ> DET NOUN
67 BINARYRULE NP^<NP> NOUN PRT
1 BINARYRULE PP^<WHADVP> ADP NOUN
1 BINARYRULE NP^<PP> NP^<NP> S^<NP>+VP^<S>
1 BINARYRULE S PP^<S> S
53 BINARYRULE NP^<SQ> NP^<NP> NP
8 BINARYRULE VP^<S> VERB VP
32 BINARYRULE VP^<VP> VERB NP^<VP>
2 BINARYRULE VP^<SQ> VERB S^<VP>
155 BINARYRULE NP ADJ NP
3 BINARYRULE NP NP^<NP> .
167 BINARYRULE NP^<PP> DET NP
2 BINARYRULE NP^<NP> PRON NP
1 BINARYRULE SBAR^<SBARQ> ADP S^<SBAR>
1 BINARYRULE NP ADJP^<NP> .
24 BINARYRULE S^<VP>+VP^<S> PRT VP^<VP>
13 BINARYRULE NP^<VP> NP^<NP> NP
1 BINARYRULE SQ NP^<SQ>+NOUN VP^<SQ>+NOUN
2 BINARYRULE SBARQ SBARQ^<SBARQ> SBARQ
9 BINARYRULE NP^<NP> ADJ NP
236 BINARYRULE WHNP^<SBARQ> DET NOUN
3 BINARYRULE VP^<VP> VERB PP^<VP>+ADP
5 BINARYRULE VP^<SQ> VERB VP^<VP>+VERB
26 BINARYRULE SBARQ WHADVP^<SBARQ> SBARQ
1 BINARYRULE QP^<NP> DET NOUN
1 BINARYRULE NP PRON NOUN
5 BINARYRULE NP ADV NP
41 BINARYRULE NP^<WHNP> ADJ NOUN
1 BINARYRULE NX^<NP> NOUN NOUN
2 BINARYRULE NP^<VP> NP^<NP> ADJP^<NP>
1 BINARYRULE ADJP^<NP> ADJ VP^<ADJP>
1 BINARYRULE S^<SBAR>+VP^<S> VERB ADJP^<VP>+ADJ
5 BINARYRULE S^<SBAR>+VP^<S> VERB VP^<VP>
6 BINARYRULE VP PRT^<VP>+PRT VP
1 BINARYRULE PP^<NP> ADV ADP
1 BINARYRULE WHNP^<VP> WHNP^<WHNP> PP^<WHNP>
1 BINARYRULE NP^<VP> DET ADJ
7 BINARYRULE NP^<PP> NUM NOUN
1 BINARYRULE NP NOUN PP^<NP>
48 BINARYRULE NP^<WHNP> NOUN NOUN
1 BINARYRULE VP NP^<VP> ADVP^<VP>+ADJ
1 BINARYRULE NP ADJP^<NP>+ADJ NP
1 BINARYRULE NP X NOUN
1 BINARYRULE VP ADV NP^<VP>
1 BINARYRULE WHNP^<SBARQ>+WHNP^<WHNP> DET NP^<WHNP>
1 BINARYRULE NP^<VP>+S^<NP> NP^<S> VP^<S>
1 BINARYRULE SBAR^<NP>+S^<SBAR> NP^<S>+NOUN VP^<S>
8 BINARYRULE NP CONJ NP^<NP>+NOUN
1 BINARYRULE VP^<SQ> VERB PP^<VP>+PP^<PP>+ADP
1 BINARYRULE NP^<SQ> ADJ NP^<NP>+NOUN
1 BINARYRULE NP^<SQ> VERB NOUN
1 BINARYRULE ADJP^<ADJP> ADJ PRT^<ADJP>+PRT
13 BINARYRULE SQ NP^<SQ> VP^<SQ>+NOUN
1 BINARYRULE VP^<SBAR> VERB NP^<VP>
1 BINARYRULE ADJP^<NP> ADJP^<ADJP> ADJP
2 BINARYRULE VP . PP^<VP>
1 BINARYRULE S^<NP>+VP^<S> VERB NP^<VP>
1 BINARYRULE VP^<S> PRT VP^<VP>+VERB
1 BINARYRULE SQ^<SBARQ>+VP^<SQ> VP^<VP> PP^<VP>
4 BINARYRULE PP^<PP> PRT NP^<PP>
1 BINARYRULE NP^<VP> NP^<NP>+DET PP^<NP>
1 BINARYRULE VP^<ADJP> ADV VERB
8 BINARYRULE VP NP^<VP> VP
1 BINARYRULE PP^<NP> PRT NOUN
3 BINARYRULE SQ^<SBARQ>+VP^<SQ> VERB SBAR^<VP>+S^<SBAR>
1 BINARYRULE VP CONJ VP^<VP>+VERB
4 BINARYRULE SQ VP^<SQ> PP^<SQ>
339 BINARYRULE NP ADJ NOUN
3 BINARYRULE VP^<VP> PRT VP^<VP>
1 BINARYRULE PP^<PP> PRT NP^<PP>+NUM
1 BINARYRULE NP X X
75 BINARYRULE SQ NP^<SQ>+PRON VP^<SQ>
1 BINARYRULE VP^<S> VERB WHNP^<VP>
3 BINARYRULE PP^<NP> ADP VP^<PP>
7 BINARYRULE PP^<VP> ADP S^<PP>+VP^<S>
1 BINARYRULE NP^<WHNP> ADJP^<NP> NP
164 BINARYRULE NP NOUN NP
2 BINARYRULE WHADVP^<SBARQ> WHADVP^<WHADVP> PP^<WHADVP>
3 BINARYRULE NP^<S> . PRON
2 BINARYRULE NP^<NP> NP^<NP>+NOUN NP
1 BINARYRULE NP^<VP> NP^<NP> SBAR^<NP>+S^<SBAR>
2 BINARYRULE NP^<PP> NP^<NP> SBAR^<NP>+S^<SBAR>
1 BINARYRULE NP^<VP> ADJ NP^<NP>
1 BINARYRULE VP . VP^<VP>
1 BINARYRULE S^<VP> NP^<S>+PRON VP^<S>+VERB
3 BINARYRULE VP NP^<VP> S^<VP>+VP^<S>
1 BINARYRULE PP^<SQ> PRT NP^<PP>
2 BINARYRULE VP VERB PP^<VP>+ADP
3 BINARYRULE NP NP^<NP> NOUN
2 BINARYRULE S^<NP>+VP^<S> VERB PP^<VP>
653 BINARYRULE SQ^<SBARQ> VERB NP^<SQ>
10 BINARYRULE NP . NOUN
11 BINARYRULE NP^<WHNP> NP^<NP> NOUN
1 BINARYRULE NP NUM .
7 BINARYRULE NP^<NP> NP^<NP> NOUN
1 BINARYRULE NP^<PP> VERB NOUN
1 BINARYRULE SBAR^<VP> WHNP^<SBAR>+DET S^<SBAR>+VP^<S>
1 BINARYRULE VP^<NP> PRT VP^<VP>+VERB
247 BINARYRULE SBARQ SQ^<SBARQ>+VP^<SQ> .
1 BINARYRULE NP^<NP> NOUN NUM
2 BINARYRULE VP^<NP> VERB NP^<VP>+NOUN
1 BINARYRULE SQ^<SBARQ> VERB NP^<SQ>+X
2 BINARYRULE SBAR^<SQ> ADP S^<SBAR>
5 BINARYRULE PP^<NP> ADP S^<PP>+VP^<S>
3 BINARYRULE NP NOUN NP^<NP>
1 BINARYRULE NP^<NP> PRON PRT
1 BINARYRULE SBAR^<SBARQ> WHADVP^<SBAR>+ADV S^<SBAR>+VP^<S>
1 BINARYRULE SQ^<SBARQ> VERB S^<SQ>+VP^<S>
9 BINARYRULE SBAR^<VP> ADP S^<SBAR>
2 BINARYRULE QP ADP NUM
358 BINARYRULE NP^<SQ> NP^<NP> PP^<NP>
7 BINARYRULE PP^<NP> ADP NP^<PP>+NUM
1 BINARYRULE ADJP NOUN VERB
28 BINARYRULE NP^<PP> NOUN NP
3 BINARYRULE NP X .
1 BINARYRULE ADJP^<NP> NOUN ADJ
1 BINARYRULE SQ^<SBARQ> VERB ADJP^<SQ>+ADJ
1 BINARYRULE VP NP^<VP>+NOUN SBAR^<VP>
3 BINARYRULE WHNP^<SBARQ> PRON NP^<WHNP>
1 BINARYRULE VP PRT^<VP>+PRT SBARQ^<VP>
1 BINARYRULE ADJP^<NP> NUM ADJ
198 BINARYRULE PP^<NP> ADP NP^<PP>+NOUN
1 BINARYRULE VP NP^<VP>+NP^<NP> PP^<VP>
1 BINARYRULE SQ NP^<SQ>+NOUN ADJP^<SQ>+ADJ
2 BINARYRULE PP^<NP> ADP NOUN
1 BINARYRULE WHPP^<SBARQ> ADP WHNP^<WHPP>+PRON
27 BINARYRULE NP^<SQ> ADJ NOUN
2 BINARYRULE PP^<ADJP> ADP S^<PP>+VP^<S>
6 BINARYRULE WHNP^<WHPP> DET NP^<WHNP>
4 BINARYRULE SQ NP^<SQ> ADJP^<SQ>+ADJ
1 BINARYRULE ADJP ADJ PP^<ADJP>+ADP
4 BINARYRULE PP^<WHADVP> ADP NP^<PP>
4 BINARYRULE PP^<SQ> PP^<PP> PP^<PP>
1 BINARYRULE WHPP^<SBAR> PRT WHNP^<WHPP>+DET
13 BINARYRULE PP^<VP> PRT NP^<PP>
1 BINARYRULE SQ NP^<SQ>+PRON ADJP^<SQ>
1 BINARYRULE NP^<PP> NP^<NP>+NUM NP
2 BINARYRULE ADJP^<SQ> ADV ADJP
96 BINARYRULE VP^<SQ> VERB PP^<VP>
3 BINARYRULE SQ NP^<SQ>+NOUN SQ
2 BINARYRULE VP CONJ VERB
2 BINARYRULE SQ NP^<SQ> ADJP^<SQ>
1 BINARYRULE VP^<S> NOUN NP^<VP>
2 BINARYRULE VP^<NP> ADVP^<VP>+ADV VP
5 BINARYRULE NP NOUN NUM
1 BINARYRULE NP^<VP> NP^<NP> PP^<NP>+PRT
1 BINARYRULE PP^<NP> ADV PP
4 BINARYRULE NP ADJP^<NP> NP
1 BINARYRULE SBAR WHNP^<SBAR> SBAR
1 BINARYRULE VP^<VP> VERB PRT^<VP>+PRT
1 BINARYRULE S^<VP> NP^<S>+NUM VP^<S>
4 BINARYRULE NP^<PP> ADJ NP
1 BINARYRULE NP^<SQ> NP^<NP> NP^<NP>+ADVP^<NP>
505 BINARYRULE SBARQ WHNP^<SBARQ> SBARQ
2 BINARYRULE WHADJP^<SBARQ> ADV ADV
3 BINARYRULE WHNP^<WHNP> WHADJP^<WHNP> NOUN
1 BINARYRULE NP CONJ NP^<NP>+NUM
2 BINARYRULE NP^<SQ> NP^<NP>+DET PP^<NP>
1 BINARYRULE PP^<ADJP> PRT NP^<PP>
2 BINARYRULE NP . ADJP^<NP>+ADJ
145 BINARYRULE NP^<SQ> NOUN NOUN
1 BINARYRULE WHNP^<VP> DET NOUN
2 BINARYRULE ADJP . ADJP
1 BINARYRULE NP^<VP>+NP^<NP> DET NP
2 BINARYRULE WHNP^<WHNP> ADV ADV
1 BINARYRULE SQ VP^<SQ>+VERB NP^<SQ>
3 BINARYRULE VP NP^<VP>+NOUN S^<VP>+VP^<S>
1 BINARYRULE VP NP^<VP>+PRON PP^<VP>
1 BINARYRULE ADJP^<VP> ADP WHNP^<ADJP>+PRON
4 BINARYRULE VP VERB PP^<VP>
5 BINARYRULE S^<PP>+VP^<S> VERB PP^<VP>
1 BINARYRULE NP^<PP> NOUN PP^<NP>
21 BINARYRULE NP NUM NOUN
5 BINARYRULE NP^<WHNP> NUM NP
3 BINARYRULE NP^<PP> NOUN .
1 BINARYRULE NP^<NP>+ADVP^<NP> . ADVP
2 BINARYRULE NP NOUN SBAR^<NP>
1 BINARYRULE ADVP^<SQ> ADV NP^<ADVP>
2 BINARYRULE NP^<VP> NP^<NP>+NOUN NP
10 BINARYRULE NP^<SQ> NP^<NP> NP^<NP>
14 BINARYRULE VP^<SQ> VERB NP^<VP>+NOUN
1 BINARYRULE NP NOUN X
1 BINARYRULE ADJP^<NP> ADVP^<ADJP> VERB
16 BINARYRULE NP^<WHNP> ADJ NP
14 BINARYRULE NP DET NP
1 BINARYRULE WHADVP^<WHADVP> ADV ADV
4 BINARYRULE S^<SBAR>+VP^<S> VERB PP^<VP>
4 BINARYRULE SBAR^<SQ> WHADVP^<SBAR>+ADV S^<SBAR>
60 BINARYRULE VP^<SQ> VERB VP
1 BINARYRULE NP^<SQ> QP^<NP> PP^<NP>
1 BINARYRULE PP^<VP> ADP NP^<PP>+VERB
1 BINARYRULE NP^<PP> VERB NP^<NP>+NOUN
1 BINARYRULE PP^<ADJP> ADP NP^<PP>+ADJ
2 BINARYRULE NP^<SQ> ADJ NP^<NP>
1 BINARYRULE WHNP^<SBAR> DET NP^<WHNP>
283 BINARYRULE SBARQ WHADVP^<SBARQ>+ADV SBARQ
19 BINARYRULE NP^<PP> NP^<NP> NOUN
8 BINARYRULE NP^<VP> NP^<NP> NOUN
2 BINARYRULE S^<VP> NP^<S>+NOUN VP^<S>
4 BINARYRULE NP^<NP> NUM NP
1 BINARYRULE NP^<PP> QP^<NP> NOUN
1 BINARYRULE PP ADP SBAR^<PP>
5 BINARYRULE VP VERB NP^<VP>
8 BINARYRULE VP^<S> VERB VP^<VP>+VERB
2 BINARYRULE VP ADVP^<VP>+ADV VP^<VP>+VERB
1 BINARYRULE NP^<VP> NP^<NP>+NOUN NP^<NP>
2 BINARYRULE SBAR^<VP>+S^<SBAR> NP^<S> VP^<S>
1 BINARYRULE VP^<NP> ADVP^<VP>+ADV VERB
2 BINARYRULE S^<SBAR>+VP^<S> VERB S^<VP>
6 BINARYRULE NP^<NP> PRON NOUN
1 BINARYRULE NP NOUN ADVP^<NP>+ADV
8 BINARYRULE SQ^<SBARQ> VERB NP^<SQ>+DET
1 BINARYRULE NP^<PP> NP^<NP> VP^<NP>
3 BINARYRULE S^<PP>+VP^<S> VERB NP^<VP>
64 BINARYRULE NP^<NP> NOUN NP
1 BINARYRULE WHADJP^<SBARQ> ADV ADJP^<WHADJP>
1 BINARYRULE VP NP^<VP> SBAR^<VP>
2 BINARYRULE NP^<SQ> DET ADJ
1 BINARYRULE VP^<S> VERB NP^<VP>+NOUN
12 BINARYRULE NP^<PP> PRON NOUN
13 BINARYRULE SQ NP^<SQ>+DET PP^<SQ>
11 BINARYRULE WHNP^<WHPP> DET NOUN
7 BINARYRULE ADJP^<NP> ADJ ADJ
1 BINARYRULE VP PP^<VP> VP
11 BINARYRULE NP^<VP> ADJ NOUN
1 BINARYRULE WHNP^<SBARQ> WHNP^<WHNP> NP^<WHNP>+NOUN
1 BINARYRULE ADJP^<NP> . ADJP
1 BINARYRULE VP . NP^<VP>+S^<NP>
16 BINARYRULE NP^<SQ> . NP
2 BINARYRULE WHNP^<SBARQ> ADV ADJ
1 BINARYRULE VP VP^<VP> SBAR^<VP>
2 BINARYRULE VP^<SQ> VERB ADVP^<VP>+ADV
1 BINARYRULE VP^<VP> VP^<VP>+VERB VP
12 BINARYRULE VP NP^<VP>+NOUN PP^<VP>
10 BINARYRULE VP NP^<VP> VP^<VP>
55 BINARYRULE WHNP^<SBARQ> WHADJP^<WHNP> NOUN
1 BINARYRULE SQ NP^<SQ>+NOUN ADVP^<SQ>
1 BINARYRULE ADVP^<SQ> . ADVP
1 BINARYRULE NP^<VP>+QP^<NP> DET NUM
1 BINARYRULE ADJP CONJ ADJP
1 BINARYRULE ADJP^<WHADJP> ADJ PP^<ADJP>
8 BINARYRULE S^<SBAR>+VP^<S> VERB NP^<VP>
1 BINARYRULE PP^<VP> NP^<PP> PP
18 BINARYRULE NP^<WHNP> NOUN NP
1 BINARYRULE NP ADJ .
1 BINARYRULE VP NP^<VP>+NUM PP^<VP>
1 BINARYRULE ADJP CONJ ADJP^<ADJP>
26 BINARYRULE NP^<WHNP> NOUN PP^<NP>
1 BINARYRULE NP NP^<NP> NP
4 BINARYRULE PP^<VP> PP^<PP> PP^<PP>
1 BINARYRULE SBARQ SQ^<SBARQ>+VP^<SQ> SBARQ
1 BINARYRULE VP VP^<VP> PP^<VP>
1 BINARYRULE ADVP^<SQ> ADVP^<ADVP> PP^<ADVP>
5 BINARYRULE S^<SBAR> NP^<S>+PRON VP^<S>+VERB
1 BINARYRULE SBAR^<SQ>+S^<SBAR> NP^<S> VP^<S>
3 BINARYRULE SQ^<SBARQ>+VP^<SQ> VERB S^<VP>+VP^<S>
9 BINARYRULE NP^<NP> NP^<NP> NP
8 BINARYRULE SQ NP^<SQ> NP^<SQ>
1 BINARYRULE NP^<PP>+QP^<NP> ADJ QP
1 BINARYRULE S^<NP> NP^<S> VP^<S>
1 BINARYRULE NP^<NP> . DET
20 BINARYRULE NP^<NP> ADJ NOUN
1 BINARYRULE NP^<SQ> NP^<NP>+NOUN NP^<NP>
1 BINARYRULE SQ NP^<SQ> NP^<SQ>+NOUN
3 BINARYRULE VP^<S> VERB PP^<VP>+ADP
1 BINARYRULE NP VERB PP^<NP>
3 BINARYRULE SBARQ PP^<SBARQ> SBARQ
120 BINARYRULE SQ^<SBARQ>+VP^<SQ> VERB NP^<VP>
17 BINARYRULE NP ADJ NP^<NP>
3 BINARYRULE VP PRT^<VP>+PRT PP^<VP>
9 BINARYRULE SBAR^<NP>+S^<SBAR>+VP^<S> PRT VP^<VP>
2 BINARYRULE VP^<NP> VERB VP
1 BINARYRULE PP^<S> ADP NP^<PP>
70 BINARYRULE SQ^<SBARQ>+VP^<SQ> VERB VP
31 BINARYRULE NP^<VP> NOUN NOUN
1 BINARYRULE VP . VP
2 BINARYRULE VP . NP^<VP>
1 BINARYRULE VP^<SQ> VERB ADJP^<VP>
5 BINARYRULE VP^<PP> VERB NP^<VP>
1 BINARYRULE ADJP^<SQ> ADJ PP^<ADJP>+PRT
1 BINARYRULE VP^<VP> VP^<VP> NP^<VP>
1 BINARYRULE NP^<NP> NOUN .
2 BINARYRULE WHNP^<SBARQ> WHNP^<WHNP>+DET PP^<WHNP>
1 BINARYRULE SBARQ VP^<SBARQ> .
169 BINARYRULE PP^<VP> ADP NP^<PP>
2 BINARYRULE VP S^<VP> PP^<VP>
1 BINARYRULE VP NP^<VP>+PRON ADJP^<VP>+ADJ
1 BINARYRULE NP^<NP> X X
1 BINARYRULE PP^<VP> ADP NP^<PP>+PRON
1 BINARYRULE NP^<SQ> NP^<NP> S^<NP>
1 BINARYRULE NP^<ADVP> ADJ NOUN
20 BINARYRULE NP ADJP^<NP> NOUN
1 BINARYRULE PP^<PP> PRT NP^<PP>+DET
1 BINARYRULE NP^<S> NP^<NP> NP
2 BINARYRULE PP^<ADJP> ADP NP^<PP>+NOUN
1 BINARYRULE S^<VP> NP^<S> S
2 BINARYRULE NP^<S> NOUN NP
49 BINARYRULE NP^<PP> NOUN NOUN
1 BINARYRULE SQ^<SBAR>+VP^<SQ> VERB NP^<VP>
2 BINARYRULE VP^<VP> VERB SBAR^<VP>
1 BINARYRULE PP^<VP> ADP NP^<PP>+ADJ
2 BINARYRULE SBARQ WHADVP^<SBARQ>+ADV SQ^<SBARQ>
2 BINARYRULE NP VERB .
1 BINARYRULE WHNP^<SBARQ> WHADJP^<WHNP> PP^<WHNP>
1 BINARYRULE SQ^<SBARQ>+VP^<SQ> VERB SBAR^<VP>
15 BINARYRULE WHNP^<WHNP> DET NOUN
3 BINARYRULE WHADVP^<SBARQ> ADV ADJ
1 BINARYRULE VP NOUN PP^<VP>+ADP
1 BINARYRULE NP^<NP>+PP^<NP> PP^<PP> PP^<PP>
1 BINARYRULE NP^<VP> PRON .
2 BINARYRULE ADJP ADJ ADJ
3 BINARYRULE SQ NP^<SQ>+NOUN PP^<SQ>
1 BINARYRULE ADVP^<ADVP> ADV PP^<ADVP>
1 BINARYRULE SBAR^<VP>+S^<SBAR> NP^<S> S
808 BINARYRULE SBARQ WHNP^<SBARQ>+PRON SBARQ
25 BINARYRULE NP^<PP> NP^<NP> NP
45 BINARYRULE NP . NP
1 BINARYRULE PP^<VP> . PP
20 BINARYRULE NP^<NP> NP^<NP> PP^<NP>
1 BINARYRULE VP^<VP> VERB WHNP^<VP>
1 BINARYRULE S^<SBAR>+VP^<S> VERB NP^<VP>+NP^<NP>
1 BINARYRULE SQ VP^<SQ> SBAR^<SQ>
1 BINARYRULE VP^<S> ADVP^<VP>+ADV VP
3 BINARYRULE S^<SBAR>+VP^<S> VERB VP
20 BINARYRULE NP CONJ NP^<NP>
2 BINARYRULE VP ADVP^<VP>+ADV PP^<VP>
1 BINARYRULE PP^<SBAR> ADP NP^<PP>+NOUN
1 BINARYRULE VP NP^<VP>+NOUN ADVP^<VP>
1 BINARYRULE NP^<VP> ADV NP
20 BINARYRULE WHNP^<SBARQ> WHADJP^<WHNP> NP^<WHNP>
90 BINARYRULE NP NOUN .
1 BINARYRULE NP VERB PRT
7 BINARYRULE VP^<S> VERB PP^<VP>
1 BINARYRULE NP ADJ NUM
5 BINARYRULE NP^<SQ> NP^<NP>+NOUN NP
3 BINARYRULE S^<SBAR> NP^<S> VP^<S>+VERB
1 BINARYRULE NP^<NP> ADJP^<NP> ADVP^<NP>
15 BINARYRULE NP NUM NP
1 BINARYRULE NP PP^<NP> PP^<NP>
1 BINARYRULE ADJP^<VP> DET ADJ
1 BINARYRULE WHNP^<WHPP> DET S^<WHNP>
46 BINARYRULE NP^<VP> DET NOUN
1 BINARYRULE VP VERB VP
1 BINARYRULE NP^<WHNP> . NP
5 BINARYRULE NP X NP
4 BINARYRULE PP^<VP> PRT NP^<PP>+NOUN
17 BINARYRULE VP^<SQ> VERB S^<VP>+VP^<S>
3 BINARYRULE SBAR^<VP> WHADVP^<SBAR>+ADV S^<SBAR>
1 BINARYRULE NP PP^<NP> VP^<NP>
3 BINARYRULE SBARQ SBAR^<SBARQ> SBARQ
1 BINARYRULE NP^<S> NP^<NP> SBAR^<NP>
2 BINARYRULE VP PP^<VP>+ADP PP^<VP>
1 BINARYRULE S^<PP>+VP^<S> VERB VP
1 BINARYRULE NP^<PP> DET NP^<NP>
4 BINARYRULE NP^<S> ADJ NOUN
29 BINARYRULE VP^<S> VERB NP^<VP>
1 BINARYRULE S^<PP>+VP^<S> VERB ADVP^<VP>+ADV
2 BINARYRULE ADJP^<NP> ADJ PP^<ADJP>
1 BINARYRULE VP^<SQ> VP^<VP> NP^<VP>+NOUN
1 BINARYRULE SBAR^<NP> WHPP^<SBAR> S^<SBAR>
1 BINARYRULE WHNP^<SBARQ> WHNP^<WHNP> NP^<WHNP>
138 BINARYRULE NP^<PP> DET NOUN
2 BINARYRULE S^<VP> NP^<S>+PRON VP^<S>
3 BINARYRULE PP^<ADVP> ADP NP^<PP>
15 BINARYRULE NP . NP^<NP>+NOUN
2 BINARYRULE S^<PP>+VP^<S> VERB ADJP^<VP>+ADJ
8 BINARYRULE SQ^<SBARQ> VERB ADJP^<SQ>
1 BINARYRULE VP^<VP> VERB NP^<VP>+QP^<NP>
1 BINARYRULE QP^<NP> ADJ QP
1 BINARYRULE NP^<PP> NP^<NP> NX^<NP>
172 BINARYRULE SQ NP^<SQ> VP^<SQ>+VERB
3 BINARYRULE VP^<SQ> VERB PP^<VP>+PRT
1 BINARYRULE NP^<VP> DET NP^<NP>
20 BINARYRULE NP^<NP> . NP
1 BINARYRULE SQ NP^<SQ> NP^<SQ>+VERB
1 BINARYRULE SQ ADV SQ
6 BINARYRULE NP VERB NOUN
1 BINARYRULE VP^<S> VERB ADJP^<VP>+ADJ
1 BINARYRULE VP^<S> VERB WHADJP^<VP>
1 BINARYRULE VP ADVP^<VP>+ADV VP
1 BINARYRULE NP^<NP> NP^<NP>+NOUN VP^<NP>
4 BINARYRULE NP^<S> DET NOUN
2 BINARYRULE NP^<PP> NP^<NP>+NOUN VP^<NP>
1 BINARYRULE NP^<PP> NP^<NP>+NOUN SBAR^<NP>
1 BINARYRULE SQ NP^<SQ>+S^<NP> VP^<SQ>
1 BINARYRULE VP NP^<VP> VERB
7 BINARYRULE PP^<PP> ADP NP^<PP>+NOUN
11 BINARYRULE SQ NP^<SQ> PP^<SQ>+ADP
3 BINARYRULE WHADVP^<SBARQ> ADV PP^<WHADVP>
1 BINARYRULE WHADVP^<WHADVP> ADV WHADVP
22 BINARYRULE SQ^<SBARQ>+VP^<SQ> VERB PP^<VP>
2 BINARYRULE SQ NP^<SQ>+X VP^<SQ>+NOUN
1 BINARYRULE SBAR^<VP>+VP^<SBAR> PRT VP^<VP>
1 BINARYRULE VP PP^<VP>+PRT PP^<VP>
3 BINARYRULE PP^<NP> PP^<PP> PP^<PP>
3 BINARYRULE VP ADV VP^<VP>
1 BINARYRULE SBAR^<NP>+S^<SBAR> NP^<S>+PRON VP^<S>+VERB
19 BINARYRULE WHNP^<SBARQ> WHNP^<WHNP> PP^<WHNP>
1 BINARYRULE ADVP CONJ ADV
1 BINARYRULE NP^<SQ> DET X
1 BINARYRULE NP^<NP> NP^<NP> ADJ
1 BINARYRULE S^<SBAR>+VP^<S> . VP
1 BINARYRULE PP^<VP> ADP NOUN
62 BINARYRULE SQ NP^<SQ>+NOUN VP^<SQ>
1 BINARYRULE PP^<VP> NP^<PP>+NUM PP^<PP>
2 BINARYRULE NP NOUN ADJ
1436 BINARYRULE SBARQ SQ^<SBARQ> .
22 BINARYRULE VP^<VP> VERB PP^<VP>
1 BINARYRULE NP^<VP> NUM NUM
1 BINARYRULE S^<NP>+VP^<S> PRT VP
3 BINARYRULE WHNP^<SBARQ> PRON NOUN
10 BINARYRULE NP^<VP> NOUN NP
